use treinamento

--LISTA 4)

--PARTE A)O nome de todos os itens que já foram pedidos (fazer uma versão com DISTINCT e uma com GROUP BY);
		SELECT p.NMPRODUCT
		FROM PRODUCTREQUEST pr
		INNER JOIN PRODUCT p ON pr.CDPRODUCT = p.CDPRODUCT
		GROUP BY NMPRODUCT;


 --PARTE B ) O nome do produto, o número de vezes que ele foi pedido e a quantidade total pedida;
		 SELECT PRODUCT.NMPRODUCT, COUNT(PRODUCTREQUEST.CDREQUEST), SUM(PRODUCTREQUEST.QTAMOUNT ) 
		 FROM PRODUCT
		 INNER JOIN PRODUCTREQUEST ON PRODUCT.CDPRODUCT= PRODUCTREQUEST.CDPRODUCT
		 INNER  JOIN REQUEST ON PRODUCTREQUEST.CDREQUEST=REQUEST.CDREQUEST
		 GROUP BY PRODUCT.NMPRODUCT


 --PARTE C) O nome do fornecedor, o total em estoque dos produtos fornecidos pelo fornecedor, a média de preço dos produtos fornecidos e quantos produtos ele fornece;
		 SELECT SUPPLIER.NMSUPPLIER, SUM( PRODUCT.QTSTOCK), AVG(PRODUCT.VLPRICE), COUNT(PRODUCT.CDSUPPLIER) 
		 FROM PRODUCT
		 INNER JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER=PRODUCT.CDSUPPLIER
		 GROUP BY SUPPLIER.NMSUPPLIER


 --PARTE D).O nome do cliente, seu telefone, o valor da maior compra, o valor da menor compra, o total comprado e a média de valor comprado, ordenado por maior compra decrescente;
		 SELECT CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE, MAX(REQUEST.VLTOTAL) AS MaiorCompra, MIN(REQUEST.VLTOTAL) AS MenorCompra, SUM(REQUEST.VLTOTAL) AS SomaCompras, AVG(REQUEST.VLTOTAL) AS MediaCompras
		 FROM REQUEST
		 INNER JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
		 GROUP BY CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE
		 ORDER BY MAX(REQUEST.VLTOTAL) DESC

 --PARTE E)A data do pedido, o nome do cliente, quantos produtos distintos ele pediu, o valor total do pedido (baseado nos valores da tabela productrequest), a média de valores do pedido (baseado nos valores da tabela productrequest) ordenado pela quantidade de produtos distintos pedidos;


		 SELECT REQUEST.DTREQUEST, CUSTOMER.NMCUSTOMER,COUNT( PRODUCT.NMPRODUCT) AS QUANTOSPRODUTOS, SUM(PRODUCTREQUEST.VLUNITARY * PRODUCTREQUEST.QTAMOUNT) AS SOMADOSVALORES,AVG(PRODUCTREQUEST.VLUNITARY * PRODUCTREQUEST.QTAMOUNT) AS MEDIA
		 FROM PRODUCTREQUEST
		 INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
		 INNER JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
		 INNER JOIN CUSTOMER ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST AND REQUEST.CDCUSTOMER=CUSTOMER.CDCUSTOMER
		 GROUP BY REQUEST.DTREQUEST, CUSTOMER.NMCUSTOMER


 --PARTE F) O nome do fornecedor e quantos produtos ele fornece, para todos os fornecedores que fornecem mais que um produto;
		 SELECT SUPPLIER.NMSUPPLIER, COUNT(PRODUCT.CDSUPPLIER) AS QuantiaDeProdutos
		 FROM PRODUCT
		INNER JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER= PRODUCT.CDSUPPLIER
		GROUP BY SUPPLIER.NMSUPPLIER
		HAVING COUNT(PRODUCT.CDSUPPLIER) >1


--PARTE G) O nome do produto, o número de vezes que ele foi pedido e a quantidade total pedida para produtos que foram pedidos menos que 2 vezes;
		SELECT PRODUCT.NMPRODUCT,COUNT(REQUEST.CDREQUEST) AS NumPedidos, SUM(  PRODUCTREQUEST.QTAMOUNT) AS QuantidadeTotal
		FROM PRODUCTREQUEST
		INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT=PRODUCTREQUEST.CDPRODUCT
		INNER JOIN REQUEST ON REQUEST.CDREQUEST=PRODUCTREQUEST.CDREQUEST
		GROUP BY PRODUCT.NMPRODUCT
		HAVING COUNT(PRODUCT.CDPRODUCT) <2


--PARTE H)O nome do cliente, o produto, o valor gasto com o produto, quantas vezes ele foi pedido pelo cliente e o nome do fornecedor. Somente para produtos em que o cliente gastou mais de R$1.000,00, ordenado por cliente e produto.
		SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, SUM(PRODUCTREQUEST.VLUNITARY * PRODUCTREQUEST.QTAMOUNT), COUNT(REQUEST.CDCUSTOMER), SUPPLIER.NMSUPPLIER
		FROM PRODUCTREQUEST
		INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT=PRODUCTREQUEST.CDPRODUCT
		INNER JOIN REQUEST ON REQUEST.CDREQUEST=PRODUCTREQUEST.CDREQUEST
		INNER JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER=PRODUCT.CDSUPPLIER
		INNER JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER= REQUEST.CDCUSTOMER
		GROUP BY CUSTOMER.NMCUSTOMER,PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER
		HAVING SUM(PRODUCTREQUEST.VLUNITARY * PRODUCTREQUEST.QTAMOUNT)>1000
		ORDER BY CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT;

